### ISSUE TITLE
Lifecycling Scales

### ISSUE THREAD

**Issue by leonidr-da** [digital-asset/contingent-claims#10]
If we have
```
Scale {k = DecimalConst 1000.0, claim = When {predicate = DecimalEqu (DecimalObs "Alice",DecimalConst 0.0), claim = One "USD"}}
```

then when it is lifecycled, we get
```
When {predicate = DecimalEqu (DecimalObs "Alice",DecimalConst 0.0), claim = One "USD"}"
```

I think that there are 2 correct (from a valuation perspective) outcomes. Either retain the Scale on the outside or push it inside the When. The original paper says
> If you acquire (scale o c) then you acquire cat the same moment, except that all the rights and obligations of c are multiplied by the value of the observable o at the moment of acquisition.

I interpret that as saying that the right thing to do is the latter; to push it inside of `When`. That makes sense to me now as the `Observable` is dependent on when you acquire the contract not on the `When` observation.

**Comment by lucianojoublanc-da** [comment]
To your last point, think of the observable, say `O`, as a function of `t`, so if we take `t` to be the number of days from today, and say the first claim is due on day 1, then we'd have something like this in pseudo-code for the outer case:

```
Scale O(0) (When (time == O(1) _)
```
and the latter for the inner case:
```
When (time == O(1)) (Scale (O(1) _)
```
So generally, they're not the same. But in the particular example you gave they are equivalent as the scale factor is a constant. i.e. it doesn't depend on `t`. But if that was not the case, say you were scaling by the "amount of money in an account at time t", then they would likely be different.

But to your first point, I do agree that this doesn't appear right. I don't think the outer `Scale` should be consumed.

**Comment by leonidr-da** [comment]
I think _if_ the outer `Scale` is consumed than the inner values need to be increased. Sorry, I think "push it inside" is confusing. If we had a `Scale O(t)` on the outside and it is `t` now, we would have a `Scale O(0)` inside. The `O` is doing more work for our lib than in the original paper.
