### ISSUE TITLE
Add a default `Show` and `Eq` instance for `Claim`

### ISSUE THREAD

**Issue by lucianojoublanc-da** [digital-asset/contingent-claims#23]
There are examples of this in `Test`.

They use a language extension `UndecidableInstances` which is why I didn't include them in the core `dar`. However, having them is really inconvenient as you can't run anything in repl or in a script.

**Comment by matteolimberto-da** [comment]
This is being addressed in https://github.com/digital-asset/contingent-claims/pull/39/ and https://github.com/digital-asset/contingent-claims/pull/45
