### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by leonidr-da** [digital-asset/contingent-claims#31]
@lucianojoublanc-da How should we handle releases? Both in terms of new functionality to this library and to the Daml SDK?

We probably don't want care about new versions of the SDK so much as the underlying Daml-LF. What if we suffix each version of this library with the DamlLF version that it supports. So we can have a tag here such as 0.0.0-1.14 ?

**Comment by lucianojoublanc-da** [comment]
We also need to account for https://github.com/digital-asset/daml-ctl, which this project depends on.

My initial thought is that contingent-claims can be used with `data-dependencies` so the SDK version shouldn't matter i.e. there should be backward compatibility if depending on it using `data-dependencies` in your `daml.yaml` file. I was just going to go for 'semantic versioning', seeing as it's popular and also what we use for the core `daml` SDK repo. How does that sound?

**Comment by leonidr-da** [comment]
As long as we document what Daml-LF each version of contingent claims supports then this sounds great.

**Comment by lucianojoublanc-da** [comment]
cc @matteolimberto-da @johan-da

**Comment by lucianojoublanc-da** [comment]
This has now been implemented with #45
