### ISSUE TITLE
Cannot model `Cond` `Expr` correctly.

### ISSUE THREAD

**Issue by lucianojoublanc-da** [digital-asset/contingent-claims#34]
`Cond` should translate to a mathematical `Expr`ession `E[I_{t >= t'} * c + I_{t < t'} c']`. The `I` is the indicator function, which is 1 if the expression in brackets is true, and 0 otherwise. The trick is that the two things we are adding together are mutually exclusive, i.e. the expressions in brackets are the complements of each other. So it reduces to either `E[c]` or `E[c']`.
However, in the actual daml implementation, the indicator function is defined as always being an expression of the form `a <= b`. So the closest thing to the complement would be `b <= a`, but of course, this doesn't work, in the case when `a == b`. In this case, both sides of the sum are true, and so your expression becomes `E[c + c']`, which is wrong!

_Originally posted by @lucianojoublanc-da in https://github.com/digital-asset/contingent-claims/pull/33#discussion_r725074734_

We can probably resolve this by changing the definition of `I`, maybe adding a `Lte` / `Gt` operator. in `Expr`. Also consider how this relates to `Indicator`, which also has restricted comparison operators.

**Comment by matteolimberto-da** [comment]
We can write the above expression as `E[I_{t >= t'} * c + (1 - I_{t >= t'} ) * c']` in order to circumvent this issue.

I will close this issue, feel free to re-open it in case you feel it has not been addressed.
