### ISSUE TITLE
Could not find module `Daml.Control.Recursion' It is not a module in the current program, or in any known package.

### ISSUE THREAD

**Issue by gtpaulose** [digital-asset/contingent-claims#38]
Can't build or test the repo because of the above error.

I have the latest daml version installed, i.e,

```
➜  contingent-claims git:(master) ✗ daml version                                                                                                                       
SDK versions:
  0.13.22
  1.17.1   (project SDK version from daml.yaml)
```

**Comment by GeorgSchneider** [comment]
`Daml.Control` is a dependency that's taken in as git submodule. Have run `git submodule init && git submodule update` as per the readme?

**Comment by gtpaulose** [comment]
Yeah sorry, can't believe i missed that! My bad
