### ISSUE TITLE
exercising `Anytime` breaks `Scale`

### ISSUE THREAD

**Issue by lJoublanc** [digital-asset/contingent-claims#57]
Losing sleep over #47, I've realised we have another bug. Exercising `Anytime` atm we remove the node altogether. We'll have the same problem as above. Instead we need to replace it with `When`

**Comment by matteolimberto-da** [comment]
I am planning to take this one up next if that's fine with you @lucianojoublanc-da.

I will start with `Anytime` but I think that the same should be done with `When` nodes when the condition is stochastic (aka stopping times): we should replace `When ( o_1(t) <= o_2(t) c` with `When (TimeGte tau) c` where `tau` is the first instant when the condition becomes True.

**Comment by matteolimberto-da** [comment]
Fixed after merging latest PR
