### ISSUE TITLE
Maxing-out protobuf recursion depth

### ISSUE THREAD

**Issue by lucianojoublanc-da** [digital-asset/contingent-claims#7]
It appears that creating very large trees is causing transactions to fail. Originally I assumed this was due to GRPC message size limits, but even after @brian-weir increased this, we're still getting crashes.

It's been suggested that this is due to recursion limits in protobuf. See below forum post:

https://discuss.daml.com/t/sandbox-grpc-exception-failed-to-parse-submission/2595/7

Several suggestions have been discussed.

1. The least effort approach would be to 'flatten' `And` nodes, by redefining them as `| And [Claim]`. This doesn't fully solve the problem, but it does mitigate the depth, based on empirical cases. The other downside of this is that we're moving away from the original representation given in the papers, and while it's isomorphic to that representation, there may be unknowns we're currently not conscious of. 
2. Redefine `Serialized.Claim` to be a template; this would mean that instead of having a single contract holding a tree of claims, you would have one contract per node; the fixed-point would then be via a `ContractId _`, and this would break the recursion limit. The downside of this is that we lose generality of the asset parameter, `a`, until we get truly generic templates in the language. It also makes it difficult to work with `[de]serialize` as this will no longer be a pure function, but an `Update` [co]Kleisli.
A further disadvantage is that passing claims across the API would be very complicated: a client program would have to fetch each node of the tree individually and then reconstruct it off-ledger. Because nodes are recursively defined, in the worst-case, fetching an instrument would take O(n) whit n being the RTT.

**Comment by leonidr-da** [comment]
Could one define an `AndN` that takes a "repeat" parameter. When we lifecycle if `N = 1` then we have the same case as regular `And`, but if N > 1 then a lifecycle would just consume the left hand side and replace with an `AndN (N-1)` ?

I know that this is less general than storing a list of potentially variable payments (or at leastpush that determination into the contained Observation?) but I think that supports the more general case.

**Comment by lucianojoublanc-da** [comment]
Not sure I get this. Let's explore a bit more. How would you for example define a series of monthly payments using this `AndN`?

The example in the current guide is something like :
```haskell
When (time == date 2021 15 05) (Scale coupon (One "USD")) `And` When (time == date 2021 15 06) (Scale coupon (One "USD")) `And` _ -- repeat other coupons here
```

**Comment by leonidr-da** [comment]
You're right, if you have something inside of the `lhs` of an `And` that changes, `AndN` does not help you.
