### ISSUE TITLE
Consider aligning developer experience to daml-finance

### ISSUE THREAD

**Issue by matteolimberto-da** [digital-asset/contingent-claims#95]
Contingent Claims:
- `daml studio` opens a project that includes the core library without the tests
- if a user opens the `test` folder, they will see errors due to missing dependencies
- in order to open the test project (which is usually used for development), one needs to `cd test && daml studio` 

Daml-Finance:
- `daml studio` opens the full project (tests included)
- the core library is packaged separately

Both approaches have pros and cons, but we could consider aligning the development experience

**Comment by lucianojoublanc-da** [comment]
Just to be clear, when you say

> `daml studio` opens

You mean executing this command from the root folder.

The tradeoff here is simplicity in the build system. CC can be built solely using the SDK (we have build scripts, but these are optional and used for the CI) plus you don't have any external dependencies like `make` etc. There was some further relevant discussion in the PR for automatic releases to the CI with @brian-weir

**Comment by matteolimberto-da** [comment]
Thanks for the feedback @lucianojoublanc-da. 

I raised this issue on the back of @markus-da 's first experience with the library and understand the trade-off, so I am tagging him in case he wishes to add something.

From my side, no strong opinion on either solution but a slight preference towards consistent user-experience.

**Comment by matteolimberto-da** [comment]
Closing this, as the library has been ported to Daml Finance
